// Mock company and report data — replace with API calls when backend is ready

const COMPANIES = [
  {
    id: 'tsla',
    name: 'Tesla, Inc.',
    ticker: 'TSLA',
    exchange: 'NASDAQ',
    country: 'United States',
    flag: '🇺🇸',
    sector: 'Consumer Discretionary',
    industry: 'Electric Vehicles',
    marketCap: 797600000000,
    enterpriseValue: 784200000000,
    currency: 'USD',
    sharePrice: 248.52,
    reportAvailability: 'preview_available',
    description: 'Electric vehicle and clean energy company',
  },
  {
    id: 'aapl',
    name: 'Apple Inc.',
    ticker: 'AAPL',
    exchange: 'NASDAQ',
    country: 'United States',
    flag: '🇺🇸',
    sector: 'Information Technology',
    industry: 'Technology Hardware',
    marketCap: 3120000000000,
    enterpriseValue: 3100000000000,
    currency: 'USD',
    sharePrice: 201.36,
    reportAvailability: 'can_generate',
    description: 'Consumer electronics and software platform',
  },
  {
    id: 'nvda',
    name: 'NVIDIA Corporation',
    ticker: 'NVDA',
    exchange: 'NASDAQ',
    country: 'United States',
    flag: '🇺🇸',
    sector: 'Information Technology',
    industry: 'Semiconductors',
    marketCap: 3200000000000,
    enterpriseValue: 3190000000000,
    currency: 'USD',
    sharePrice: 130.09,
    reportAvailability: 'can_generate',
    description: 'GPU and AI accelerator company',
  },
  {
    id: 'msft',
    name: 'Microsoft Corporation',
    ticker: 'MSFT',
    exchange: 'NASDAQ',
    country: 'United States',
    flag: '🇺🇸',
    sector: 'Information Technology',
    industry: 'Software',
    marketCap: 3040000000000,
    enterpriseValue: 3060000000000,
    currency: 'USD',
    sharePrice: 408.24,
    reportAvailability: 'can_generate',
    description: 'Cloud, productivity and enterprise software',
  },
  {
    id: 'upm-he',
    name: 'UPM-Kymmene Oyj',
    ticker: 'UPM.HE',
    exchange: 'Helsinki',
    country: 'Finland',
    flag: '🇫🇮',
    sector: 'Materials',
    industry: 'Paper & Forest Products',
    marketCap: 7720000000,
    enterpriseValue: 10500000000,
    currency: 'EUR',
    sharePrice: 20.41,
    reportAvailability: 'preview_available',
    description: 'Global forest industry company',
  },
  {
    id: 'nda-he',
    name: 'Nordea Bank Abp',
    ticker: 'NDA.HE',
    exchange: 'Helsinki',
    country: 'Finland',
    flag: '🇫🇮',
    sector: 'Financials',
    industry: 'Banks',
    marketCap: 38200000000,
    enterpriseValue: null,
    currency: 'EUR',
    sharePrice: 9.58,
    reportAvailability: 'preview_available',
    description: 'Nordic financial services group',
  },
  {
    id: 'knebv-he',
    name: 'KONE Oyj',
    ticker: 'KNEBV.HE',
    exchange: 'Helsinki',
    country: 'Finland',
    flag: '🇫🇮',
    sector: 'Industrials',
    industry: 'Industrial Machinery',
    marketCap: 18200000000,
    enterpriseValue: 19100000000,
    currency: 'EUR',
    sharePrice: 35.66,
    reportAvailability: 'can_generate',
    description: 'Elevators, escalators and building flow solutions',
  },
  {
    id: 'novo-b',
    name: 'Novo Nordisk A/S',
    ticker: 'NOVO-B.CO',
    exchange: 'Copenhagen',
    country: 'Denmark',
    flag: '🇩🇰',
    sector: 'Health Care',
    industry: 'Pharmaceuticals',
    marketCap: 298000000000,
    enterpriseValue: 305000000000,
    currency: 'DKK',
    sharePrice: 589.60,
    reportAvailability: 'can_generate',
    description: 'Diabetes and obesity pharmaceuticals leader',
  },
  {
    id: 'sterv-he',
    name: 'Stora Enso Oyj',
    ticker: 'STERV.HE',
    exchange: 'Helsinki',
    country: 'Finland',
    flag: '🇫🇮',
    sector: 'Materials',
    industry: 'Paper & Forest Products',
    marketCap: 5800000000,
    enterpriseValue: 8200000000,
    currency: 'EUR',
    sharePrice: 7.76,
    reportAvailability: 'coming_soon',
    description: 'Renewable materials, packaging and paper',
  },
  {
    id: 'amzn',
    name: 'Amazon.com, Inc.',
    ticker: 'AMZN',
    exchange: 'NASDAQ',
    country: 'United States',
    flag: '🇺🇸',
    sector: 'Consumer Discretionary',
    industry: 'E-Commerce & Cloud',
    marketCap: 2240000000000,
    enterpriseValue: 2290000000000,
    currency: 'USD',
    sharePrice: 211.35,
    reportAvailability: 'can_generate',
    description: 'E-commerce, cloud computing and advertising',
  },
];

const TESLA_PREVIEW = {
  reportId: 'report_tsla_2026_05_26',
  companyId: 'tsla',
  status: 'preview_available',
  reportDate: '2026-05-26',
  dataDate: '2026-05-25',
  price: { currency: 'USD', singleReport: 19.9, launchPrice: 9.9 },
  keyMetrics: [
    { label: 'Share Price', value: '$248.52', change: '+1.4%', positive: true },
    { label: 'Market Cap', value: '$798B', change: null },
    { label: 'Enterprise Value', value: '$784B', change: null },
    { label: 'Revenue (LTM)', value: '$97.7B', change: '+1.1%', positive: true },
    { label: 'EBIT Margin', value: '3.7%', change: '-5.2pp', positive: false },
    { label: 'EV/EBIT', value: '218x', change: null },
    { label: 'P/E (fwd)', value: '89x', change: null },
    { label: 'Div. Yield', value: '0.0%', change: null },
  ],
  previewSummary: "Tesla's current enterprise value of ~$784B embeds far more than the company's near-term automotive profitability can justify. At an EBIT margin of 3.7% and EV/EBIT of 218x, the automotive business alone accounts for a relatively small share of total implied value. The preview suggests the market is pricing in a substantial option premium for future value drivers — including Full Self-Driving software, the Robotaxi network, and energy storage. The full report maps each value driver, tests the required assumptions, and runs a reverse valuation on the path required to justify current pricing.",
  valuePoolsPreview: [
    { name: 'Automotive (Core)', pct: 38, locked: false, color: '#3D9E72' },
    { name: 'Energy & Storage', pct: 12, locked: false, color: '#6DBFA0' },
    { name: 'FSD Software Option', pct: 22, locked: true, color: '#8A9590' },
    { name: 'Robotaxi Option', pct: 23, locked: true, color: '#8A9590' },
    { name: 'Optimus / Other', pct: 5, locked: true, color: '#8A9590' },
  ],
  reverseValTeaser: 'The implied valuation requires Tesla to grow revenue to approximately $300–400B by 2030 while expanding EBIT margins to 18–22% — substantially above current performance.',
};

const SAMPLE_REPORTS = [
  {
    id: 'tesla-sample',
    companyName: 'Tesla, Inc.',
    ticker: 'TSLA',
    market: 'NASDAQ',
    title: 'Option-heavy valuation case',
    shortDescription: 'A sample showing how current automotive earnings and future option pools — Robotaxi, FSD, Optimus — can be separated and tested against current enterprise value.',
    reportType: 'AI Equity Report',
    pdfUrl: null,
    thumbnailUrl: null,
    isAvailable: false,
    tags: ['Option value', 'Reverse valuation', 'Value drivers', 'EV tech'],
  },
  {
    id: 'upm-sample',
    companyName: 'UPM-Kymmene Oyj',
    ticker: 'UPM.HE',
    market: 'Helsinki',
    title: 'Asset-backed value and profitability case',
    shortDescription: 'A sample showing how enterprise value, asset-backed businesses, segment economics, and reverse valuation can be analyzed with strict EV discipline — avoiding misleading market cap comparisons.',
    reportType: 'AI Equity Report',
    pdfUrl: null,
    thumbnailUrl: null,
    isAvailable: false,
    tags: ['Asset-heavy', 'EV/EBIT', 'Segments', 'Nordic'],
  },
  {
    id: 'nordea-sample',
    companyName: 'Nordea Bank Abp',
    ticker: 'NDA.HE',
    market: 'Helsinki',
    title: 'Bank profitability and capital return case',
    shortDescription: 'A sample showing how financial sector reports focus on profitability drivers, CET1 capital, credit quality, dividend capacity, and valuation — without standard EV framework.',
    reportType: 'AI Equity Report',
    pdfUrl: null,
    thumbnailUrl: null,
    isAvailable: false,
    tags: ['Banking', 'Capital return', 'ROE', 'Nordic'],
  },
  {
    id: 'novo-sample',
    companyName: 'Novo Nordisk A/S',
    ticker: 'NOVO-B.CO',
    market: 'Copenhagen',
    title: 'Quality compounder and pipeline optionality',
    shortDescription: 'A sample showing how a high-quality growth company with a dominant market position, strong margins, and a deep pipeline can be valued across core and option scenarios.',
    reportType: 'AI Equity Report',
    pdfUrl: null,
    thumbnailUrl: null,
    isAvailable: false,
    tags: ['Quality growth', 'Pipeline', 'GLP-1', 'Pharma'],
  },
  {
    id: 'kone-sample',
    companyName: 'KONE Oyj',
    ticker: 'KNEBV.HE',
    market: 'Helsinki',
    title: 'Finnish industrial compounder case',
    shortDescription: 'A sample showing how a Finnish mid-cap industrial with a global maintenance base, strong recurring revenues, and China exposure can be analyzed and valued.',
    reportType: 'AI Equity Report',
    pdfUrl: null,
    thumbnailUrl: null,
    isAvailable: false,
    tags: ['Industrials', 'Recurring revenue', 'Nordic', 'Mid-cap'],
  },
];

const LOCKED_SECTIONS = [
  {
    id: 'value-map',
    title: 'Full Company Value Map',
    description: 'See exactly how enterprise value is allocated across all business segments, assets, and future option pools — with the methodology behind each allocation.',
    icon: 'chart-pie',
    blurPreviewText: 'Automotive core contributes approximately 38% of total enterprise value at current market pricing. Energy & Storage adds 12%. The remaining 50% represents option value embedded in future business units that have not yet reached material profitability...',
  },
  {
    id: 'core-analysis',
    title: 'Core Investment Analysis',
    description: 'A full value driver-based analysis of business model quality, competitive position, historical performance, valuation tension, scenarios, risks, and catalysts.',
    icon: 'document',
    blurPreviewText: 'The automotive business faces increasing competitive pressure in China and Europe, while the US market remains relatively protected. FSD adoption trajectory is the single largest uncertainty factor in the valuation. Historical margin trajectory suggests...',
  },
  {
    id: 'reverse-valuation',
    title: 'Reverse Valuation',
    description: 'Understand what revenue growth, EBIT margin, and cash flow path would be required for the current valuation to make rational sense.',
    icon: 'calculator',
    blurPreviewText: 'Base scenario: Revenue CAGR of 22% through 2030, reaching $285B. EBIT margin expansion to 18% by 2028 as FSD software revenues scale. WACC assumption 9.5%. Required automotive EV contribution at base: $298B...',
  },
  {
    id: 'risks',
    title: 'Risk & Catalyst Analysis',
    description: 'Identify what could break the investment case — profitability pressure, execution risk, regulatory changes, valuation assumption failures.',
    icon: 'warning',
    blurPreviewText: 'Key downside risks: 1) FSD timeline slippage — if full autonomy is delayed 2+ years, the Robotaxi option loses material value. 2) China competition intensifies — BYD and local players continue to erode margin...',
  },
  {
    id: 'financials',
    title: 'Financial Statements & Estimates',
    description: 'Full income statement, balance sheet, and cash flow tables with consensus estimates for 2024–2027.',
    icon: 'table',
    blurPreviewText: 'Revenue: 2024A $97.7B | 2025E $107.3B | 2026E $131.2B | 2027E $162.8B\nEBIT: 2024A $3.6B | 2025E $6.8B | 2026E $14.1B | 2027E $22.4B\nEBIT margin: 2024A 3.7% | 2025E 6.3% | 2026E 10.7% | 2027E 13.8%...',
  },
  {
    id: 'pdf',
    title: 'PDF Download',
    description: 'Export the full report as a professional institutional-style PDF. Filename: Valuatum_AI_Equity_Report_TSLA_2026-05-26.pdf',
    icon: 'download',
    blurPreviewText: null,
  },
];

// Export for module use
if (typeof module !== 'undefined') {
  module.exports = { COMPANIES, TESLA_PREVIEW, SAMPLE_REPORTS, LOCKED_SECTIONS };
}
