// Pricing configuration — edit here to adjust pricing across the site

const PRICING_CONFIG = {
  currency: 'EUR',
  currencySymbol: '€',
  launchMode: true,

  tiers: [
    {
      id: 'free',
      name: 'Free Report',
      price: 0,
      launchPrice: null,
      period: null,
      description: 'See what the report covers before you commit.',
      features: [
        'Company snapshot & key metrics',
        'High-level value pool snapshot',
        'One AI-generated insight',
        'Reverse valuation teaser',
        'Visible locked sections',
      ],
      notIncluded: [
        'Full value pool analysis',
        'Core investment analysis',
        'Reverse valuation path',
        'Risk & catalyst section',
        'Financial tables',
        'PDF download',
      ],
      cta: 'Generate report',
      ctaHref: 'index.html#hero',
      featured: false,
      badge: null,
    },
    {
      id: 'single',
      name: 'Single Report',
      price: 19.90,
      launchPrice: 9.90,
      period: 'per report',
      description: 'Full institutional-style equity research report for one company.',
      features: [
        'Full company value map',
        'Complete value pool analysis',
        'Core investment analysis',
        'Reverse valuation path',
        'Risk & catalyst analysis',
        'Financial statements & estimates',
        'Investment summary',
        'PDF download',
        'Instant access',
      ],
      notIncluded: [],
      cta: 'Buy report',
      ctaHref: '#checkout',
      featured: true,
      badge: 'Launch price',
    },
    {
      id: 'credits-5',
      name: '5 Report Credits',
      price: 49,
      launchPrice: null,
      period: '€9.80 per report',
      description: 'Best value for covering a portfolio or sector. Credits never expire.',
      features: [
        'Everything in Single Report ×5',
        'Credits never expire',
        'Use on any supported company',
        'PDF download for all reports',
        'Priority generation queue',
      ],
      notIncluded: [],
      cta: 'Buy 5 credits',
      ctaHref: '#checkout',
      featured: false,
      badge: 'Popular',
    },
    {
      id: 'credits-20',
      name: '20 Report Credits',
      price: 149,
      launchPrice: null,
      period: '€7.45 per report',
      description: 'For analysts and professionals covering multiple companies regularly.',
      features: [
        'Everything in Single Report ×20',
        'Credits never expire',
        'Use on any supported company',
        'PDF download for all reports',
        'Priority generation queue',
        'Invoice available on request',
      ],
      notIncluded: [],
      cta: 'Buy 20 credits',
      ctaHref: '#checkout',
      featured: false,
      badge: 'Best value',
    },
    {
      id: 'pro',
      name: 'Pro Monthly',
      price: 79,
      launchPrice: null,
      period: 'per month',
      description: 'Unlimited reports for active analysts and finance professionals.',
      features: [
        'Unlimited report generation',
        'All report sections & PDF',
        'Report history & library',
        'Priority support',
        'Early access to new features',
        'Invoice & receipt included',
      ],
      notIncluded: [],
      cta: 'Start Pro',
      ctaHref: '#checkout',
      featured: false,
      badge: 'Coming soon',
      comingSoon: true,
    },
    {
      id: 'enterprise',
      name: 'Enterprise',
      price: null,
      launchPrice: null,
      period: 'custom',
      description: 'For institutions, advisory firms, and IR teams needing volume, custom branding, or API access.',
      features: [
        'Volume discounts',
        'Branded PDF reports',
        'API access',
        'Custom coverage lists',
        'Team accounts',
        'Dedicated support',
        'SLA & contract',
      ],
      notIncluded: [],
      cta: 'Contact sales',
      ctaHref: 'mailto:sales@valuatum.com',
      featured: false,
      badge: null,
    },
  ],
};

if (typeof module !== 'undefined') {
  module.exports = { PRICING_CONFIG };
}
