// Pricing configuration - edit here to adjust pricing across the site.

const PRICING_CONFIG = {
  currency: 'EUR',
  currencySymbol: '\u20ac',
  launchMode: false,

  tiers: [
    {
      id: 'free-sample-reports',
      name: 'Free Sample Reports',
      price: 0,
      launchPrice: null,
      period: null,
      description: 'Open full free PDF reports before you buy. No card, no account required.',
      features: [
        'Full PDF report',
        'Segment value analysis',
        'Reverse valuation',
        'Risk & catalyst analysis',
        'Financial statements',
      ],
      notIncluded: [],
      cta: 'View free samples',
      ctaHref: 'reports.html#free',
      featured: false,
      badge: null,
    },
    {
      id: 'free-sample',
      name: 'Free Sample',
      price: 0,
      launchPrice: null,
      period: null,
      description: 'Open full free PDF reports before you buy. No card, no account required.',
      features: [
        'Full PDF report',
        'Segment value analysis',
        'Reverse valuation',
        'Risk & catalyst analysis',
        'Financial statements',
      ],
      notIncluded: [],
      cta: 'View free samples',
      ctaHref: 'reports.html#free',
      featured: false,
      badge: null,
    },
    {
      id: 'existing-report',
      name: 'Existing Report',
      price: 20,
      launchPrice: null,
      period: 'per report',
      description: 'Ready AI equity reports. Full PDF with all sections.',
      features: [
        'Full PDF report',
        'Company value map',
        'Core investment analysis',
        'Reverse valuation + scenarios',
        'Risk & catalyst analysis',
        'Financial statements',
        'Investment summary',
      ],
      notIncluded: [],
      cta: 'Browse reports',
      ctaHref: 'reports.html',
      featured: true,
      badge: 'Available now',
    },
    {
      id: 'fresh-report',
      name: 'Fresh Report',
      price: 50,
      launchPrice: null,
      period: 'per report',
      description: 'Generate a new report with the latest available financial data.',
      features: [
        'Everything in Existing Report',
        'Latest available data',
        'Any supported listed company',
        'Delivered within 1 business day',
      ],
      notIncluded: [],
      cta: 'Generate fresh report',
      ctaHref: 'reports.html#order-fresh',
      featured: false,
      badge: 'Fresh',
    },
    {
      id: 'enterprise',
      name: 'Enterprise',
      price: null,
      launchPrice: null,
      period: 'custom',
      description: 'For institutions, advisory firms, and IR teams needing volume, branded outputs, or API access.',
      features: [
        'Volume discounts',
        'Branded PDF reports',
        'API access',
        'Custom coverage lists',
        'Team accounts',
        'Dedicated support',
        'SLA & contract',
      ],
      notIncluded: [],
      cta: 'Contact sales',
      ctaHref: 'mailto:contact26@valuatum.com',
      featured: false,
      badge: null,
    },
  ],
};

if (typeof module !== 'undefined') {
  module.exports = { PRICING_CONFIG };
}
