// Auto-generated by scripts/build-report-pages.mjs — maps report id -> landing-page slug.
window.REPORT_SLUGS = {
  "upm-21052026": "upm-equity-report",
  "storaenso-01062026": "stora-enso-equity-report",
  "tesla-01062026": "tesla-equity-report",
  "nvidia-13072026": "nvidia-equity-report",
  "intel-05062026": "intel-equity-report",
  "kesko-05062026": "kesko-equity-report",
  "amd-05062026": "advanced-micro-devices-equity-report",
  "nokia-05062026": "nokia-equity-report",
  "wartsila-05062026": "wartsila-equity-report",
  "recursion-02062026": "recursion-pharmaceuticals-equity-report",
  "oriola-01062026": "oriola-equity-report",
  "fortum-coverage": "fortum-equity-report",
  "orion-coverage": "orion-equity-report"
};
