// Resale reaper (Phase 2).
//
// Ends the resale window of auto-generated reports once they are older than
// RESALE_WINDOW_DAYS. Because delivered download URLs are permanent,
// the reaper NEVER deletes anything: it rewrites the sidecar to hidden, which
// removes the report from the public catalog while the PDF object — and every
// link already emailed to a buyer — keeps working. The engine's own copy
// (s3://valuatum-pdf-reports/{jobId}.pdf) is likewise untouched, so a later
// request regenerates the report with fresh data.
//
// GUARDRAIL: only reports whose sidecar carries provenance (i.e. generated by
// the reconciler) are ever touched. Curated free samples and manually added
// catalog reports have no provenance and are left alone.
//
// Runs inside the legacy always-on Express server (started from index.js,
// gated by RESALE_ENABLED) and as the worker Lambda's daily EventBridge rule
// in AWS ({action:'reap'}). Storage is the local PDF dir or S3, matching the
// reconciler's switch. REAPER_DRY_RUN (default true) logs what it would hide
// without writing anything, so targeting can be verified before it is armed.

const fs = require('fs');
const path = require('path');

function intEnv(name, fallback) {
  const value = Number.parseInt(process.env[name] || '', 10);
  return Number.isFinite(value) ? value : fallback;
}

function boolEnv(name, fallback) {
  const value = process.env[name];
  if (value == null || value === '') return fallback;
  return /^(1|true|yes|on)$/i.test(value);
}

const PDF_DIR = process.env.REPORT_PDF_DIR || '/var/www/html/reports/pdfs';
const RESALE_ENABLED = boolEnv('RESALE_ENABLED', false);
const WINDOW_DAYS = intEnv('RESALE_WINDOW_DAYS', 14);
const INTERVAL_MS = intEnv('REAPER_INTERVAL_MS', 60 * 60 * 1000);
const DRY_RUN = boolEnv('REAPER_DRY_RUN', true);

const MS_PER_DAY = 24 * 60 * 60 * 1000;

// Storage backend: S3 in Lambda (REPORT_PDF_BUCKET set), local dir on the legacy server.
const s3Store = process.env.REPORT_PDF_BUCKET ? require('./aws/pdf-store') : null;

const store = s3Store
  ? {
      async listPdfFiles() {
        return (await s3Store.listPdfs()).map(file => file.fileName);
      },
      readSidecar: fileBase => s3Store.readSidecar(`${fileBase}.pdf`).then(sidecar =>
        (sidecar && Object.keys(sidecar).length ? sidecar : null)),
      writeSidecar: (fileBase, sidecar) => s3Store.writeSidecar(`${fileBase}.pdf`, sidecar),
    }
  : {
      async listPdfFiles() {
        return fs.readdirSync(PDF_DIR).filter(file => file.toLowerCase().endsWith('.pdf'));
      },
      async readSidecar(fileBase) {
        try {
          return JSON.parse(fs.readFileSync(path.join(PDF_DIR, `${fileBase}.json`), 'utf8'));
        } catch (err) {
          return null;
        }
      },
      async writeSidecar(fileBase, sidecar) {
        const filePath = path.join(PDF_DIR, `${fileBase}.json`);
        const tmp = `${filePath}.tmp`;
        fs.writeFileSync(tmp, `${JSON.stringify(sidecar, null, 2)}\n`);
        fs.renameSync(tmp, filePath);
      },
    };

// Mirrors catalog.js: Company_DDMMYYYY.pdf -> YYYY-MM-DD. Kept as a local copy
// because catalog.js does not export it; the filename format is the contract.
function parseReportDateFromFileName(fileName) {
  const match = String(fileName || '').match(/(\d{8})(?=\.pdf$|[^0-9])/i);
  if (!match) return null;

  const raw = match[1];
  const first = Number(raw.slice(0, 2));
  const second = Number(raw.slice(2, 4));

  if (first >= 1 && first <= 31 && second >= 1 && second <= 12) {
    return `${raw.slice(4, 8)}-${raw.slice(2, 4)}-${raw.slice(0, 2)}`;
  }

  return `${raw.slice(0, 4)}-${raw.slice(4, 6)}-${raw.slice(6, 8)}`;
}

function startOfUtcDay(date) {
  return Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
}

function daysSince(dateValue, now = new Date()) {
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return 0;
  return Math.max(0, Math.floor((startOfUtcDay(now) - startOfUtcDay(date)) / MS_PER_DAY));
}

// The guardrail predicate: true only for reports the reconciler generated.
function hasProvenance(sidecar) {
  const p = sidecar && sidecar.provenance;
  return Boolean(p && (p.jobId || p.sessionId));
}

function isAlreadyHidden(sidecar) {
  return Boolean(sidecar.hidden) ||
    String(sidecar.publicationStatus || '').toLowerCase() === 'hidden';
}

// One sweep over the catalog. Returns a summary so it is testable and so the
// caller can log it. Never throws on a single bad file -- it skips and continues.
async function sweep(now = new Date()) {
  let pdfs;
  try {
    pdfs = await store.listPdfFiles();
  } catch (err) {
    console.warn('reaper: cannot list PDF catalog', err.message);
    return { scanned: 0, eligible: 0, hidden: 0 };
  }

  let eligible = 0;
  let hidden = 0;

  for (const pdfFile of pdfs) {
    const fileBase = pdfFile.replace(/\.pdf$/i, '');

    let sidecar;
    try {
      sidecar = await store.readSidecar(fileBase);
    } catch (err) {
      console.warn('reaper: cannot read sidecar for', pdfFile, err.message);
      continue;
    }

    // Guardrail: skip anything we did not generate (no provenance).
    if (!hasProvenance(sidecar)) continue;
    // Already off the catalog (Phase-1 delivery or a previous sweep).
    if (isAlreadyHidden(sidecar)) continue;

    const reportDate = parseReportDateFromFileName(pdfFile);
    if (!reportDate) continue;

    const age = daysSince(reportDate, now);
    if (age <= WINDOW_DAYS) continue;
    eligible += 1;

    if (DRY_RUN) {
      console.log(`reaper: WOULD hide ${pdfFile} (age ${age}d > window ${WINDOW_DAYS}d)`);
      continue;
    }

    try {
      await store.writeSidecar(fileBase, {
        ...sidecar,
        hidden: true,
        publicationStatus: 'hidden',
        forceVisible: false,
        resaleEndedAt: now.toISOString(),
      });
      hidden += 1;
      console.log(`reaper: hid ${pdfFile} (age ${age}d > window ${WINDOW_DAYS}d); PDF and sold links stay live`);
    } catch (err) {
      console.warn('reaper: hide failed', pdfFile, err.message);
    }
  }

  return { scanned: pdfs.length, eligible, hidden };
}

function start() {
  if (!RESALE_ENABLED) {
    console.log('Reaper not started: RESALE_ENABLED is off');
    return null;
  }
  console.log(
    `Reaper started (interval ${INTERVAL_MS}ms, window ${WINDOW_DAYS}d, ` +
    `${DRY_RUN ? 'DRY-RUN: logs only, hides nothing' : 'ARMED: hides expired resales'})`,
  );

  const run = () => {
    sweep().catch(err => console.error('reaper: sweep error:', err.message));
  };

  run();
  const timer = setInterval(run, INTERVAL_MS);
  if (timer.unref) timer.unref();
  return timer;
}

module.exports = { start, sweep, parseReportDateFromFileName, daysSince, hasProvenance };
