// Resale reaper (Phase 2).
//
// Periodically deletes the catalog display copy (PDF + sidecar) of an
// auto-generated report once it is older than RESALE_WINDOW_DAYS, ending its
// resale window. The engine's permanent copy (s3://valuatum-pdf-reports/{jobId}
// .pdf) is NOT touched, so a later request regenerates the report with fresh
// data -- deletion only removes it from the public catalog.
//
// GUARDRAIL: only reports whose sidecar carries provenance (i.e. generated by
// the reconciler) are ever deleted. Curated free samples and manually added
// catalog reports have no provenance and are left alone.
//
// Runs inside the always-on Express process (started from index.js), gated by
// RESALE_ENABLED. REAPER_DRY_RUN (default true) logs what it would delete
// without deleting anything, so targeting can be verified before it is armed.

const fs = require('fs');
const path = require('path');

function intEnv(name, fallback) {
  const value = Number.parseInt(process.env[name] || '', 10);
  return Number.isFinite(value) ? value : fallback;
}

function boolEnv(name, fallback) {
  const value = process.env[name];
  if (value == null || value === '') return fallback;
  return /^(1|true|yes|on)$/i.test(value);
}

const PDF_DIR = process.env.REPORT_PDF_DIR || '/var/www/html/reports/pdfs';
const RESALE_ENABLED = boolEnv('RESALE_ENABLED', false);
const WINDOW_DAYS = intEnv('RESALE_WINDOW_DAYS', 14);
const INTERVAL_MS = intEnv('REAPER_INTERVAL_MS', 60 * 60 * 1000);
const DRY_RUN = boolEnv('REAPER_DRY_RUN', true);

const MS_PER_DAY = 24 * 60 * 60 * 1000;

// Mirrors catalog.js: Company_DDMMYYYY.pdf -> YYYY-MM-DD. Kept as a local copy
// because catalog.js does not export it; the filename format is the contract.
function parseReportDateFromFileName(fileName) {
  const match = String(fileName || '').match(/(\d{8})(?=\.pdf$|[^0-9])/i);
  if (!match) return null;

  const raw = match[1];
  const first = Number(raw.slice(0, 2));
  const second = Number(raw.slice(2, 4));

  if (first >= 1 && first <= 31 && second >= 1 && second <= 12) {
    return `${raw.slice(4, 8)}-${raw.slice(2, 4)}-${raw.slice(0, 2)}`;
  }

  return `${raw.slice(0, 4)}-${raw.slice(4, 6)}-${raw.slice(6, 8)}`;
}

function startOfUtcDay(date) {
  return Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate());
}

function daysSince(dateValue, now = new Date()) {
  const date = new Date(dateValue);
  if (Number.isNaN(date.getTime())) return 0;
  return Math.max(0, Math.floor((startOfUtcDay(now) - startOfUtcDay(date)) / MS_PER_DAY));
}

function readSidecar(fileBase) {
  try {
    return JSON.parse(fs.readFileSync(path.join(PDF_DIR, `${fileBase}.json`), 'utf8'));
  } catch (err) {
    return null;
  }
}

// The guardrail predicate: true only for reports the reconciler generated.
function hasProvenance(sidecar) {
  const p = sidecar && sidecar.provenance;
  return Boolean(p && (p.jobId || p.sessionId));
}

// One sweep over REPORT_PDF_DIR. Returns a summary so it is testable and so the
// caller can log it. Never throws on a single bad file -- it skips and continues.
function sweep(now = new Date()) {
  let files;
  try {
    files = fs.readdirSync(PDF_DIR);
  } catch (err) {
    console.warn('reaper: cannot read REPORT_PDF_DIR', PDF_DIR, err.message);
    return { scanned: 0, eligible: 0, reaped: 0 };
  }

  const pdfs = files.filter(file => file.toLowerCase().endsWith('.pdf'));
  let eligible = 0;
  let reaped = 0;

  for (const pdfFile of pdfs) {
    const fileBase = pdfFile.replace(/\.pdf$/i, '');
    const sidecar = readSidecar(fileBase);

    // Guardrail: skip anything we did not generate (no provenance).
    if (!hasProvenance(sidecar)) continue;

    const reportDate = parseReportDateFromFileName(pdfFile);
    if (!reportDate) continue;

    const age = daysSince(reportDate, now);
    if (age <= WINDOW_DAYS) continue;
    eligible += 1;

    if (DRY_RUN) {
      console.log(`reaper: WOULD delete ${pdfFile} + sidecar (age ${age}d > window ${WINDOW_DAYS}d)`);
      continue;
    }

    let failed = false;
    for (const target of [path.join(PDF_DIR, pdfFile), path.join(PDF_DIR, `${fileBase}.json`)]) {
      try {
        fs.unlinkSync(target);
      } catch (err) {
        if (err.code !== 'ENOENT') {
          failed = true;
          console.warn('reaper: delete failed', target, err.message);
        }
      }
    }
    if (!failed) {
      reaped += 1;
      console.log(`reaper: deleted ${pdfFile} + sidecar (age ${age}d > window ${WINDOW_DAYS}d)`);
    }
  }

  return { scanned: pdfs.length, eligible, reaped };
}

function start() {
  if (!RESALE_ENABLED) {
    console.log('Reaper not started: RESALE_ENABLED is off');
    return null;
  }
  console.log(
    `Reaper started (interval ${INTERVAL_MS}ms, window ${WINDOW_DAYS}d, ` +
    `${DRY_RUN ? 'DRY-RUN: logs only, deletes nothing' : 'ARMED: deletes'})`,
  );

  const run = () => {
    try {
      sweep();
    } catch (err) {
      console.error('reaper: sweep error:', err.message);
    }
  };

  run();
  const timer = setInterval(run, INTERVAL_MS);
  if (timer.unref) timer.unref();
  return timer;
}

module.exports = { start, sweep, parseReportDateFromFileName, daysSince, hasProvenance };
